<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Промисы -->
    <!-- 1 - есть создающий код, он делпает чтото, что занимает время. Наример, загружает данные по сети. -->
    <!-- 2 - есть протреблящий код, он хочет получит результат Создающего кода, когда он будет готов -->
    <!-- Promise - это специальный обьект в js, он связывает создающий и потреблящий код вместе -->
    <!-- Синтаксис создания промиса -->

            <!-- let promise = new Promise(function(resolve, reject) {
                // функция-исполнитель (executor)
            }); -->
    <!-- Функция переданная в конструкцию new Promise, называется исполнитель. Когда промис создается запустится автоматически. Должна содержать создающий код. Ее аргуметны resolve, reject - это колбэки, которые представляет сам js. Наш код только внутри исполнителя
    Должен вызвать один из колбеков. 
    - resolve(value) - если работа завершилась успешно, с результатом value
    - reject(error) - если произошла ошибка, error - обьект ошибки

    У объекта promise, возвращаемого конструктором new Promise, есть внутренние свойства:
    state («состояние») — вначале "pending" («ожидание»), потом меняется на "fulfilled" («выполнено успешно») при вызове resolve или на "rejected" («выполнено с ошибкой») при вызове reject.
    result («результат») — вначале undefined, далее изменяется на value при вызове resolve(value) или на error при вызове reject(error).-->




    <!-- Потребители - обьект promise служит связующим звеном между создающим и потребляющим кодом(функции-потребители), который получают либо результат, либо ошибку. Функции-потребители могут быть (подписаны) с помощью методов  .then и .catch -->
    <!-- then:
            promise.then(
                function(result) { /* обработает успешное выполнение */ },
                function(error) { /* обработает ошибку */ }
            ); 
        Первый аргумент метода then - это функция, которая выполнитя, когда промис переходит в состояние (Выполнен успешно) и получает результат.
        Второй аргумент .then – функция, которая выполняется, когда промис переходит в состояние «выполнен с ошибкой», и получает ошибку.
        -->
        <!-- Пример -->
        <script>
            // let promise = new Promise(function(resolve, reject){
            //     setTimeout(() => resolve('test'), 1000)
            // })

            // promise.then(
            //     result => alert(result),
            //     error => alert(error)
            // )
            // Метод catch - обрабатывает только ошибки
            // promise.catch(alert)


            function delay(ms){
                return new Promise(function(resolve, reject){
                    setTimeout(()=>resolve('Выполнил успешно'), ms)
                })
            }

            delay(3000).then(alert)

    </script>
</body>
</html>